# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnstreetParkingBays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_geom', models.CharField(blank=True, db_column='The_geom', max_length=255, null=True)),
                ('meter_id', models.CharField(blank=True, db_column='Meter_id', max_length=255, null=True)),
                ('bay_id', models.FloatField(blank=True, db_column='Bay_id', null=True)),
                ('marker_id', models.CharField(blank=True, db_column='Marker_id', max_length=255, null=True)),
                ('last_edit', models.FloatField(blank=True, db_column='Last_edit', null=True)),
                ('rd_seg_id', models.FloatField(blank=True, db_column='Rd_seg_id', null=True)),
                ('rd_seg_dsc', models.CharField(blank=True, db_column='Rd_seg_dsc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'onstreet_parking_bays',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OnstreetParkingBaySensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_id', models.FloatField(blank=True, db_column='Bay_id', null=True)),
                ('st_marker_id', models.CharField(blank=True, db_column='St_marker_id', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, db_column='Lat', null=True)),
                ('lon', models.FloatField(blank=True, db_column='Lon', null=True)),
            ],
            options={
                'db_table': 'onstreet_parking_bay_sensors',
                'managed': True,
            },
        ),
    ]
